# Welcome to Jekyll!
#

# Site settings
title: Ingrid Elias #title
description: UX/UI Designer & Developer  #description
owner: Ingrid Elias # or company name
first_published: 2015 # if migrating another site, the year of your first publish
email: ingrid3lias@gmail.com
baseurl: "/ingrid3lias.github.io" # the subpath of your site, e.g. /blog
url: "http://ingrid3lias.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/ingrid3lias
  github: https://github.com/ingrid3lias
  linkedin-square: https://www.linkedin.com/in/ingridelias
  instagram: https://www.instagram.com/ingrid3lias/
  email: /contact/
  google_analytics: "UA-75972383-1"
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
